# Generated by Django 2.1.1 on 2018-10-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mews', '0002_auto_20181009_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mew',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
