# Generated by Django 2.1.1 on 2018-10-11 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mews', '0003_auto_20181011_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mew',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
